In [4]:
import pandas as pd
import numpy as np
data=pd.read_csv('wns_train.csv')
out=data['is_promoted']
data['previous_year_rating'].fillna(3,inplace=True)
data['education'].fillna("Bacherlor's",inplace=True)
inp_data=data.drop(['is_promoted','employee_id'],1)

In [5]:
data2=pd.get_dummies(inp_data,drop_first=True)
data2.head()

no_of_trainings  age  previous_year_rating  length_of_service  \
0                1   35                   5.0                  8   
1                1   30                   5.0                  4   
2                1   34                   3.0                  7   
3                2   39                   1.0                 10   
4                1   45                   3.0                  2   

   KPIs_met >80%  awards_won?  avg_training_score  department_Finance  \
0              1            0                  49                   0   
1              0            0                  60                   0   
2              0            0                  50                   0   
3              0            0                  50                   0   
4              0            0                  73                   0   

   department_HR  department_Legal  ...  region_region_6  region_region_7  \
0              0                 0  ...                0                1   
1              0                 0  ...                0                0   
2              0                 0  ...                0                0   
3              0                 0  ...                0                0   
4              0                 0  ...                0                0   

   region_region_8  region_region_9  education_Bacherlor's  \
0                0                0                      0   
1                0                0                      0   
2                0                0                      0   
3                0                0                      0   
4                0                0                      0   

   education_Below Secondary  education_Master's & above  gender_m  \
0                          0                           1         0   
1                          0                           0         1   
2                          0                           0         1   
3                          0                           0         1   
4                          0                           0         1   

   recruitment_channel_referred  recruitment_channel_sourcing  
0                             0                             1  
1                             0                             0  
2                             0                             1  
3                             0                             0  
4                             0                             0  

[5 rows x 54 columns]

In [6]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(data2,out,test_size=0.3,random_state=48)

In [7]:
from sklearn.tree import DecisionTreeClassifier
dtree_mod=DecisionTreeClassifier()
dtree_mod.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [8]:
ypred= dtree_mod.predict(xtest)

In [9]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(ytest,ypred))
print(classification_report(ytest,ypred))

0.8963084595268503
              precision    recall  f1-score   support

           0       0.95      0.94      0.94     15030
           1       0.41      0.46      0.43      1413

    accuracy                           0.90     16443
   macro avg       0.68      0.70      0.69     16443
weighted avg       0.90      0.90      0.90     16443



In [10]:
data.isnull().sum()

employee_id             0
department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [11]:
data["education"].mode()

0    Bachelor's
dtype: object

In [12]:
len(ypred)

16443

In [13]:
test=pd.read_csv('wns_test.csv')
test['previous_year_rating'].fillna(3,inplace=True)
test['education'].fillna("Bacherlor's",inplace=True)
inp_test=test.drop(['employee_id'],1)

In [14]:
test2=pd.get_dummies(inp_test,drop_first=True)

In [15]:
ypred1= dtree_mod.predict(test2)

In [16]:
final=pd.DataFrame()

In [17]:
final['employee_id']=test['employee_id']
final['is_promoted']=ypred1

In [18]:
final.to_csv("output1.csv")

In [19]:
des_mod=DecisionTreeClassifier()

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
rf_mod=RandomForestClassifier()

In [21]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
folds=KFold(n_splits=5,shuffle=True,random_state=100)
hyper_params=[{"criterion":["gini",'entropy']}]
model=GridSearchCV(rf_mod,param_grid=hyper_params,scoring='accuracy',cv=folds)
model.fit(xtrain,ytrain)

C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\skl

GridSearchCV(cv=KFold(n_splits=5, random_state=100, shuffle=True),
             error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                    

In [22]:
model.best_params_

{'criterion': 'entropy'}

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
folds=KFold(n_splits=5,shuffle=True,random_state=100)
hyper_params=[{"criterion":["entropy"],'max_depth':[5,10,15,20,25,28]}]
model1=GridSearchCV(rf_mod,param_grid=hyper_params,scoring='accuracy',cv=folds)
model1.fit(xtrain,ytrain)

C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\skl

GridSearchCV(cv=KFold(n_splits=5, random_state=100, shuffle=True),
             error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                    

In [24]:
model1.best_params_

{'criterion': 'entropy', 'max_depth': 25}

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
folds=KFold(n_splits=5,shuffle=True,random_state=100)
hyper_params=[{"criterion":["entropy"],'max_depth':[20],'min_samples_leaf':[20,30,50]}]
model2=GridSearchCV(rf_mod,param_grid=hyper_params,scoring='accuracy',cv=folds)
model2.fit(xtrain,ytrain)

C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\skl

GridSearchCV(cv=KFold(n_splits=5, random_state=100, shuffle=True),
             error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                    

In [25]:
from sklearn.model_selection import GridSearchCV
rf_mod=RandomForestClassifier()
hyper_params=[{'min_samples_split':[10,20,30,50]}]
model3=GridSearchCV(rf_mod,param_grid=hyper_params,scoring='accuracy',cv=folds)
model3.fit(xtrain,ytrain)

C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\skl

GridSearchCV(cv=KFold(n_splits=5, random_state=100, shuffle=True),
             error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                    

In [42]:
model3.best_params_

{'min_samples_split': 10}

In [1]:
from sklearn.model_selection import GridSearchCV
rf_mod=RandomForestClassifier()
hyper_params=[{'n_estimators':[10,20,30,50,100]}]
model4=GridSearchCV(rf_mod,param_grid=hyper_params,scoring='accuracy',cv=folds)
model4.fit(xtrain,ytrain)

NameError: name 'RandomForestClassifier' is not defined

In [ ]:
model4.best_params_

In [28]:
from sklearn.model_selection import GridSearchCV
rf_mod=RandomForestClassifier()
hyper_params=[{'max_features':[10,20,30,50,100]}]
model5=GridSearchCV(rf_mod,param_grid=hyper_params,scoring='accuracy',cv=folds)
model5.fit(xtrain,ytrain)

C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\skl

ValueError: max_features must be in (0, n_features]

"criterion":['entropy'],'max_depth':[20],'min_samples_leaf':[20],'min_samples_split': [20]

In [29]:
model5.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [30]:
rf_mod=RandomForestClassifier(criterion='entropy',max_depth=20,min_samples_leaf=20,min_impurity_split=20,n_estimators=275,max_features=50)

In [31]:
model.fit(xtrain,ytrain)

C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Gowrav Tata\Anaconda3\lib\site-packages\skl

GridSearchCV(cv=KFold(n_splits=5, random_state=100, shuffle=True),
             error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                    

In [32]:
ypred=model.predict(xtest)

In [33]:
accuracy_score(ypred,ytest)

0.9300006081615277

Random Forest and Bagging Technique
In the bagging technique only row sampling is permitted while in case of Random Forest both column and row are allowed

Decision Tree is a part of Random Forest

In [34]:
yproba=model.predict_proba(xtest)

In [35]:
yproba

array([[0.7, 0.3],
       [1. , 0. ],
       [1. , 0. ],
       ...,
       [1. , 0. ],
       [0.9, 0.1],
       [1. , 0. ]])

In [36]:
ypred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [37]:
list(yproba)

[array([0.7, 0.3]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.9, 0.1]),
 array([1., 0.]),
 array([0.9, 0.1]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.8, 0.2]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.8, 0.2]),
 array([0.8, 0.2]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.9, 0.1]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.8, 0.2]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.8, 0.2]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.9, 0.1]),
 array([0.9, 0.1]),
 array([0.4, 0.6]),
 array([0.8, 0.2]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.9, 0.1]),
 array([1., 0.]),
 array([1., 0.]),
 array([0.8, 0.2]),
 array([0.8, 0.2]),
 array([0.8, 0.2]),
 array([0.8, 0.2]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1., 0.]),
 array([1.

In [39]:
out=np.zeros([len(yproba),1])
out[yproba[:,1]>0.3]=1
out

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [38]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.94      0.99      0.96     15030
           1       0.75      0.28      0.41      1413

    accuracy                           0.93     16443
   macro avg       0.84      0.63      0.68     16443
weighted avg       0.92      0.93      0.91     16443



In [40]:
print(classification_report(ytest,out))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96     15030
           1       0.52      0.43      0.47      1413

    accuracy                           0.92     16443
   macro avg       0.73      0.69      0.71     16443
weighted avg       0.91      0.92      0.91     16443



In [48]:
from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=5))
ada_mod=ada.fit(xtrain,ytrain)
ada_pred=ada_mod.predict(xtest)

In [49]:
print(classification_report(ytest,ada_pred))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96     15030
           1       0.70      0.38      0.50      1413

    accuracy                           0.93     16443
   macro avg       0.82      0.68      0.73     16443
weighted avg       0.92      0.93      0.92     16443



In [62]:
adab=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=3),learning_rate=0.5,n_estimators=40)

In [63]:
adab.fit(xtrain,ytrain)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(class_weight=None,
                                                         criterion='gini',
                                                         max_depth=3,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort=False,
                                                         random_state=None,
                             

In [64]:
adab_pred=adab.predict(xtest)

In [65]:
print(classification_report(ytest,adab_pred))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97     15030
           1       0.92      0.34      0.50      1413

    accuracy                           0.94     16443
   macro avg       0.93      0.67      0.73     16443
weighted avg       0.94      0.94      0.93     16443



In [67]:
adab_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [72]:
adab_td=adab.predict(test2)

In [73]:
final_adab_mod=pd.DataFrame()
final_adab_mod['employee_id']=test_data['employee_id']
final_adab_mod['is_promoted']=adab_td

In [74]:
final_adab_mod.to_csv('output_adab.csv')